<?php
return array (
  'app' => 'Portal',
  'model' => 'AdminOrder',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '匹配系统',
  'icon' => 'exchange',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'provideHelp',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '提供帮助',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'getHelp',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '接受帮助',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'provideSplit',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '提供拆分',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'getSplit',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '接受拆分',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'trading',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '交易中的订单',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'tradeSuccess',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '交易完成的订单',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'timeoutPay',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '超时未打款',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'timeoutGathering',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '超时未收款',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminOrder',
      'action' => 'complainOrder',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '投诉订单管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);