<?php
return array (
  'app' => 'User',
  'model' => 'Indexadmin',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '0',
  'name' => '用户管理',
  'icon' => 'group',
  'remark' => '',
  'listorder' => '10',
  'children' => 
  array (
    array (
      'app' => 'User',
      'model' => 'Indexadmin',
      'action' => 'default1',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '用户组',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'User',
          'model' => 'Indexadmin',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '本站用户',
          'icon' => 'leaf',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'User',
              'model' => 'Indexadmin',
              'action' => 'ban',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '拉黑会员',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'User',
              'model' => 'Indexadmin',
              'action' => 'cancelban',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '启用会员',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'User',
          'model' => 'Oauthadmin',
          'action' => 'index',
          'data' => '',
          'type' => '1',
          'status' => '1',
          'name' => '第三方用户',
          'icon' => 'leaf',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'User',
              'model' => 'Oauthadmin',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '第三方用户解绑',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
  ),
);